using System.Linq;
using UnityEngine;

namespace Prebut
{
    [AddComponentMenu("Prebut/Setup Pre-Rendered Background")]
    public class SetupPreRenderedBackground : MonoBehaviour
    {
        [SerializeField, HideInInspector] private Material _referenceMaterial;
        [SerializeField, HideInInspector] private Mesh _quadMesh;
        [SerializeField, HideInInspector] private GameObject _sceneInstanceRoot;
        [SerializeField, HideInInspector] private OrthographicCameraCenter _orthographicCameraCenter;
        [SerializeField, HideInInspector] private Camera _backgroundCamera;
        [SerializeField, HideInInspector] private GameObject _backgroundQuad;
        [SerializeField, HideInInspector] private MeshRenderer _backgroundRenderer;
        [SerializeField, HideInInspector] private Camera _sceneCamera;

        [SerializeField, HideInInspector] private int _hiddenLayers = 0;

        [SerializeField, Tooltip("Prefab of scene which contains lights, camera, and collider meshes")]
        private GameObject _scene;
        [SerializeField, Tooltip("The pre-rendered color information")]
        private Texture2D _colorTexture;
        [SerializeField, Tooltip("The pre-rendered depth information")]
        private Texture2D _depthTexture;
        [SerializeField, Layer, Tooltip("The layer used to render the background")]
        private int _backgroundLayer;
        [SerializeField, Tooltip("Extra data asset generated by prebat add-on for blender")]
        private TextAsset _extraData;
        [SerializeField, Tooltip("Should a component for controlling panning and zooming of orthographic renders be added?")]
        private bool _addOrthographicCameraCenterController = true;
        [SerializeField, Tooltip("The color which the transparent parts and area outside the background texture will be cleared with")]
        private Color _backgroundColor = new Color(0.1921569f, 0.3019608f, 0.4745098f, 0f);
        [SerializeField, Tooltip("Should the background renderer clear colors before drawing?")]
        private bool _shouldClearColors = true;

#if UNITY_EDITOR
        public Texture2D ColorTexture => _colorTexture;
        public GameObject Scene => _scene;
        public int BackgroundLayer => _backgroundLayer;
        public Color BackgroundColor => _backgroundColor;
        public TextAsset ExtraData => _extraData;
        public Mesh QuadMesh => _quadMesh;
        public bool AddOrthographicCameraCenterController => _addOrthographicCameraCenterController;
        public MeshRenderer BackgroundRenderer
        {
            get => _backgroundRenderer;
            set => _backgroundRenderer = value;
        }
        public GameObject SceneInstanceRoot
        {
            get => _sceneInstanceRoot;
            set => _sceneInstanceRoot = value;
        }
        public OrthographicCameraCenter OrthographicCameraCenter
        {
            get => _orthographicCameraCenter;
            set => _orthographicCameraCenter = value;
        }
        public Camera BackgroundCamera
        {
            get => _backgroundCamera;
            set => _backgroundCamera = value;
        }
        public GameObject BackgroundQuad
        {
            get => _backgroundQuad;
            set => _backgroundQuad = value;
        }
        public int HiddenLayers => _hiddenLayers;
        public bool ShouldClearColors => _shouldClearColors;
#endif

        public Camera SceneCamera
        {
            get => _sceneCamera;
            set => _sceneCamera = value;
        }

        private void Start()
        {
            if (_referenceMaterial == null)
            {
                Debug.LogError("ReferenceMaterial is null");
                return;
            }
            if (_sceneCamera == null)
            {
                Debug.LogError("SceneCamera is null");
                return;
            }
            if (_colorTexture == null)
            {
                Debug.LogError("ColorTexture is null");
                return;
            }
            if (_depthTexture == null)
            {
                Debug.LogError("DepthTexture is null");
                return;
            }
            var mat = new Material(_referenceMaterial);
            _backgroundRenderer.material = mat;
            mat.SetMatrix("_Perspective", _sceneCamera.projectionMatrix);
            mat.SetFloat("_Near", _sceneCamera.nearClipPlane);
            mat.SetFloat("_Far", _sceneCamera.farClipPlane);
            mat.SetTexture("_RenderedTex", _colorTexture);
            mat.SetTexture("_DepthTex", _depthTexture);
        }
    }
}
